version: '3'
services:
  app: # reference name when running service with docker-compose
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./build:/var/www/deadlydapper
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"



# build project:
# $   docker-compose build

# run project
# $   docker-compose run app sh -c "django-admin.py startproject app ./"


# run unit tests
# $   docker-compose run app sh -c "pytohn manage.py test && flake8"


# main project
# $   docker-compose run app sh -c "python manage.py startapp core"


# make DB migrations
# $   docker-compose run app sh -c "python manage.py makemigrations core"
      